### ISSUE TITLE
Loading from .json; traits

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#20]
Only personal traits show up after loading from .json (the slots themselves are missing / not displayed).

**Comment by Liraal2** [comment]
Should be fixed after re-adding import support, please check.

**Comment by Shinga13** [comment]
Not fixed, but now Boff stations are affected as well, see issue #47.

**Comment by nehpetsca** [comment]
Upon importing any exported file that contains BOFF abilities, the section of boxes for the BOFF abilities is mostly blank (the top section header is visible, no boxes or other BOFF sections headers are visible).  Only a single BOFF ability needs to be set to cause this import failure -- if no BOFF abilities are set at all, it imports fine and shows the empty BOFF slots.

Additional: If importing an ability this way, switching to a different ship can sometimes show some of the other boxes/headers, but not all of them.  Switching to an alternate ship and back to the original ship leaves the display in the fully broken format.

**Comment by nehpetsca** [comment]
Import works fine for all trait sets if there are no BOFF abilities to load.  If BOFF abilities are set in import file: Traits load empty, but are editable.

Trace back:
File main.py, line 515, importCallback self.setupSpaceBuildFrames()
File main.py, line 918, setupSpaceBuildFrames, self.setupSpaceBoffFrame(self.backend['shipHtml'])
File main.py, line 870, setupSpaceBoffFrame, self.backend['i_'+boffSan][i] = image
KeyError: 'i_Tactical' [this will be whatever the 'top' BOFF groups is, i_Science when science, etc]

**Comment by nehpetsca** [comment]
All of space and ground should now export and import to the same revision of SETS.
Some versions may still change the JSON structure before it's locked for release.
